server:
  port: 9091
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-micro-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/UserAmazonDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update